version: "3.9"

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7475:7474"
      - "7688:7687"
    env_file:
      - ./.env
  api:
    image: loxeinc/fact-check-api
    build: .
    depends_on:
      - neo4j
    volumes:
      - ./src:/fact-check/src
    ports:
      - "4000:4000"
    command:
      - "npm"
      - "start"
    env_file:
      - ./.env
